name: mapata
description: Mapata.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  firebase_core: ^1.20.0
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  get_it: ^7.2.0
  retrofit: ^3.0.1+1
  floor: ^1.3.0
  ionicons: ^0.1.2
  dio: ^4.0.6
  shared_preferences: ^2.0.15
  firebase_auth: ^3.4.2
  google_sign_in: ^5.4.0
  sqflite: ^2.0.2+1
  floor_generator: ^1.3.0
  firebase_database: ^9.0.20
  cloud_firestore: ^3.4.2
  cloud_firestore_odm: ^1.0.0-dev.24
  json_annotation: ^4.6.0
  google_maps_flutter: ^2.1.10
  http: ^0.13.4
  json_serializable: ^6.3.1
  flutter_google_places: ^0.3.0
  geolocator: ^9.0.1
  intl: ^0.17.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.2.0
  cloud_firestore_odm_generator: ^1.0.0-dev.28

flutter:
  uses-material-design: true
  generate: true # local resources (intl localization language)
  assets:
    - assets/markers/