// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACCAujpdzAnazR3Of-gq6C_IBPxLyPm0o',
    appId: '1:49357132653:android:45a900e0fee64ed1ab8064',
    messagingSenderId: '49357132653',
    projectId: 'mapata-1943d',
    storageBucket: 'mapata-1943d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVoDW78RSdwHszLRjMujkKn6_eit7mBDo',
    appId: '1:49357132653:ios:3da964b0dc9f2edfab8064',
    messagingSenderId: '49357132653',
    projectId: 'mapata-1943d',
    storageBucket: 'mapata-1943d.appspot.com',
    iosClientId: '49357132653-qp0t4i3jr7trch5pbe8ldsm5tpkvjq8s.apps.googleusercontent.com',
    iosBundleId: 'com.fgmontero',
  );
}
